[theme]
theme = "native"

[icons]
icons = "awesome4"

[[block]]
block = "nvidia_gpu"
interval = 1
format = " $icon GT 1030 $utilization $temperature $clocks "

[[block]]
block = "amd_gpu"
format = " $icon $utilization "
format_alt = " $icon MEM: $vram_used_percents ($vram_used/$vram_total) "
interval = 1

[[block]]
block = "battery"
format = " $icon $percentage "
full_format = " $icon "
empty_format = " $icon "
not_charging_format = " $icon "
missing_format = " $icon "
full_threshold=95
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "backlight"


[[block]]
block = "cpu"
format = '<span color="#66cccc" font_family="unifont">$barchart</span> $utilization'
interval = 1

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90


[[block]]
block = "sound"


[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"

[[block]]
block = "time"
interval = 0.2
format = "  $timestamp.datetime(f:'%a %d %b %Y')  $timestamp.datetime(f:'%I:%M')"
